/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-10 05:54:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp._0510국민보험공단.DAO_005fDTO_005f국민;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>국민보험공단</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        form {width: 1200px; }\r\n");
      out.write("        form table {}\r\n");
      out.write("        form table tbody{}\r\n");
      out.write("        form table tbody tr{}\r\n");
      out.write("        form table tbody tr th{}\r\n");
      out.write("        form table tbody tr td{}\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <form name=\"signup_form\" id=\"signupForm\" method=\"post\" action=\"./signUp_insert_action.jsp\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">사업장관리번호<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"saup_grbh\" id=\"saupGrbh\" type=\"text\"><button>사업장 관리번호 확인방법</button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">사업장기호<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"saup_giho\" id=\"saupGiho\" type=\"text\" placeholder=\"사업장관리번호확인 버튼을 클릭하여 검증하시면 자동입력 됩니다.\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">단위사업장기호<i>*</i></th>\r\n");
      out.write("                        <td><button>단위사업장검색</button><input name=\"gaib_yb\" id=\"gaibYb\" type=\"text\"><button>가입여부 확인하기(실명확인)</button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">아이디<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"user_id\" id=\"userId\" type=\"text\" placeholder=\"영문+숫자 6~10자 이내 아이디 입력\"><button>아이디 중복 검색</button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">비밀번호<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"user_pw1\" id=\"userPw1\" type=\"text\" placeholder=\"영문+숫자+특수문자(!@#$) 각 1자 이상 포함하여 9~12자 이내 비밀번호 입력\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">비밀번호확인<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"user_pw2\" id=\"userPw2\" type=\"text\" placeholder=\"영문+숫자+특수문자(!@#$) 각 1자 이상 포함하여 9~12자 이내 비밀번호 입력\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">비밀번호 분실 시 확인 <br>질문<i>*</i></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <select name=\"sel_pw\" id=\"selPw\">\r\n");
      out.write("                                <option value selected=\"selected\">질문을 선택하세요.</option>\r\n");
      out.write("                                <option value=\"나의 아버지 성함은?\">나의 아버지 성함은?</option>\r\n");
      out.write("                                <option value=\"나의 그리운 고향은?\">나의 그리운 고향은?</option>\r\n");
      out.write("                                <option value=\"나의 첫째아이 이름은?\">나의 첫째아이 이름은?</option>\r\n");
      out.write("                                <option value=\"나의 초등학교 이름은?\">나의 초등학교 이름은?</option>\r\n");
      out.write("                                <option value=\"나의 보물 제1호는?\">나의 보물 제1호는?</option>\r\n");
      out.write("                                <option value=\"기억에 남는 추억의 장소는?\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("                                <option value=\"나의 인생 좌우명은?\">나의 인생 좌우명은?</option>\r\n");
      out.write("                                <option value=\"내가 좋아하는 캐릭터는?\">내가 좋아하는 캐릭터는?</option>\r\n");
      out.write("                                <option value=\"추억하고 싶은 날짜가 있다면?\">추억하고 싶은 날짜가 있다면?</option>\r\n");
      out.write("                                <option value=\"인상 깊게 읽은 책 이름은?\">인상 깊게 읽은 책 이름은?</option>\r\n");
      out.write("                                <option value=\"내가 가장 존경하는 인물은?\">내가 가장 존경하는 인물은?</option>\r\n");
      out.write("                                <option value=\"가장 기억에 남는 선생님 성함은?\">가장 기억에 남는 선생님 성함은?</option>\r\n");
      out.write("                                <option value=\"내가 받았던 선물 중 기억에 남는 선물은?\">내가 받았던 선물 중 기억에 남는 선물은?</option>\r\n");
      out.write("                                <option value=\"INPUT\">직접입력</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">비밀번호 분실 시 확인 <br>답변<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"pwbs_ok\" id=\"pwbsOk\" type=\"text\" placeholder=\"조회 답변은 띄어쓰기 포함 10자 이내\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">전화번호<i>*</i></th>\r\n");
      out.write("                        <td><input name=\"user_hp\" id=\"userHp\" type=\"text\" placeholder=\"“-(하이픈)” 없이 입력 (예 : 01012345678)\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">이메일<i>*</i></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"form_email\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <input class=\"input_email\" name=\"input_email\" id=\"inputEmail\" type=\"text\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <select name=\"email_domain_select\" id=\"emailDomainSelect\">\r\n");
      out.write("                                        <option value selected=\"selected\">직접입력</option>\r\n");
      out.write("                                        <option value=\"naver.com\">네이버</option>\r\n");
      out.write("                                        <option value=\"nate.com\">네이트</option>\r\n");
      out.write("                                        <option value=\"daum.net\">다음(한메일)</option>\r\n");
      out.write("                                        <option value=\"yahoo.co.kr\">야후</option>\r\n");
      out.write("                                        <option value=\"hotmail.com\">핫메일(MSN)</option>\r\n");
      out.write("                                        <option value=\"gmail.com\">Gmail</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"row\">소식지 수신여부<i>*</i></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <input name=\"sosic_ok\" id=\"sosicOk\" value=\"Y\" checked=\"checked\" type=\"radio\"><label for=\"infoYn1\">받음</label>\r\n");
      out.write("                                <input name=\"sosic_ok\" id=\"sosicOk\" value=\"N\" checked=\"checked\" type=\"radio\"><label for=\"infoYn2\">안받음 (공단의 다양한 소식을 무료로 만나보세요)</label>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            <button type=\"submit\">확인</button>\r\n");
      out.write("            <button type=\"submit\">취소</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
