/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-11 04:46:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp._0511kurly과제.쇼핑몰고객관리;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\n");
      out.write("    <title>회원가입 제발 되라</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"wrap\">\n");
      out.write("        <main id=\"signUp\">\n");
      out.write("            <section id=\"section1\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"gap\">\n");
      out.write("                        <div class=\"title\">\n");
      out.write("                            <h2>회원가입</h2>\n");
      out.write("                            <p><span><i></i>필수입력사항</span></p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"content\">\n");
      out.write("                            <form name=\"signup_form\" id=\"signUpFrom\" method=\"post\" action=\"./signup_action.jsp\">\n");
      out.write("                                <ul>\n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label htmlFor=\"userId\">아이디<i>*</i></label>\n");
      out.write("                                            <div class=\"center-box\">\n");
      out.write("                                                <input type=\"text\" maxlength={16} name=\"user_id\" id=\"userId\" placeholder=\"아이디를 입력해주세요\">\n");
      out.write("                                            </div>\n");
      out.write("                                            <button type=\"button\">중복확인</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label htmlFor=\"userPw\">비밀번호<i>*</i></label>\n");
      out.write("                                            <div class=\"center-box\">\n");
      out.write("                                                <input \n");
      out.write("                                                    type='password'  \n");
      out.write("                                                    maxLength={16} \n");
      out.write("                                                    name='user_pw' \n");
      out.write("                                                    id='userPw' \n");
      out.write("                                                    placeholder='비밀번호를 입력해주세요' \n");
      out.write("                                                />\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label htmlFor=\"userName\">이름<i>*</i></label>\n");
      out.write("                                            <div class=\"center-box\">\n");
      out.write("                                                <input \n");
      out.write("                                                    type='text' \n");
      out.write("                                                    name='user_name' \n");
      out.write("                                                    id='userName' \n");
      out.write("                                                    placeholder='이름을 입력해주세요' \n");
      out.write("                                                />\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label htmlFor=\"userEmail\">이메일<i>*</i></label>\n");
      out.write("                                            <div class=\"center-box\">\n");
      out.write("                                                <input \n");
      out.write("                                                    type='email' \n");
      out.write("                                                    name='user_email' \n");
      out.write("                                                    id='userEmail' \n");
      out.write("                                                    placeholder='이메일을 입력해주세요' \n");
      out.write("                                                />\n");
      out.write("                                            </div>\n");
      out.write("                                            <button  \n");
      out.write("                                                type='button'\n");
      out.write("                                                onClick={onClickUserEmailOk}\n");
      out.write("                                            >중복확인</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label htmlFor=\"userHp\">휴대폰<i>*</i></label>\n");
      out.write("                                            <div class=\"center-box\">\n");
      out.write("                                                <input \n");
      out.write("                                                    type='text'  \n");
      out.write("                                                    maxLength={11} \n");
      out.write("                                                    name='user_hp' \n");
      out.write("                                                    id='userHp' \n");
      out.write("                                                    placeholder='숫자만 입력해주세요' \n");
      out.write("                                                />\n");
      out.write("                                            </div>\n");
      out.write("                                            <button class=\"hp-num-btn\" type='button'>인증번호 받기</button>\n");
      out.write("                                            <button class=\"hp-num-btn\" type='button'>다른번호 인증</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label htmlFor=\"userAddress1\">주소<i>*</i></label>\n");
      out.write("                                            <div class=\"center-box\">\n");
      out.write("                                                <input \n");
      out.write("                                                    type='text' \n");
      out.write("                                                    name='user_addr' \n");
      out.write("                                                    id='userAddr' \n");
      out.write("                                                    placeholder='주소 검색' \n");
      out.write("                                                    />\n");
      out.write("                                                <h5>샛별배송</h5>\n");
      out.write("                                                \n");
      out.write("                                                <h6>배송지에 따라 상품 정보가 달라질 수 있습니다.</h6>\n");
      out.write("                                            </div>\n");
      out.write("                                        \n");
      out.write("                                            <button \n");
      out.write("                                                class=\"addr-research-btn\"\n");
      out.write("                                                type='button'\n");
      out.write("                                            >재검색</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>                                 \n");
      out.write("                                    <li>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label>성별</label>\n");
      out.write("                                            <div class=\"center-box gender\">\n");
      out.write("                                                <label><input type='radio' name='user_gender' id='userMale' value='남자'/>남자</label>\n");
      out.write("                                                <label><input type='radio' name='user_gender' id='userFemale' value='여자'/>여자</label>\n");
      out.write("                                                <label><input type='radio' name='user_gender' id='userNone' value='선택안함'/>선택안함</label>\n");
      out.write("                                            </div>                                            \n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                    <div>\n");
      out.write("                                            <label>생년월일</label>\n");
      out.write("                                            <div class=\"center-box birth\">\n");
      out.write("                                                <div class=\"birth-box\">\n");
      out.write("                                                    <ul>\n");
      out.write("                                                        <li>\n");
      out.write("                                                            <input \n");
      out.write("                                                                type=\"text\" \n");
      out.write("                                                                maxLength={10} \n");
      out.write("                                                                name='user_birth' \n");
      out.write("                                                                id='userBirthYear' \n");
      out.write("                                                                placeholder='생년월일'\n");
      out.write("                                                            /></li>\n");
      out.write("                                \n");
      out.write("                                                       \n");
      out.write("                                                    </ul>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>                                       \n");
      out.write("                                    </div>\n");
      out.write("                                    </li>   \n");
      out.write("                                    <li>\n");
      out.write("                                        <label for=\"\">추가 입력사항<br>\n");
      out.write("                                            <input class=\"radio\" type=\"radio\" name=\"user_add\" id=\"add\" value=\"친구초대 추천인 아이디\">친구초대 추천인 아이디\n");
      out.write("                                            <input class=\"radio\" type=\"radio\" name=\"user_add\" id=\"add\" value=\"참여 이벤트명\">참여 이벤트명<br>\n");
      out.write("                                        </label>\n");
      out.write("                                    </li> \n");
      out.write("                                    <li>\n");
      out.write("                                        <label for=\"\">이용약관동의<br>\n");
      out.write("                                            <input class=\"chk1\" type=\"checkbox\" name=\"user_chk1\" id=\"chk1\" value=\"이용약관동의\">이용약관동의\n");
      out.write("                                            <input class=\"chk1\" type=\"checkbox\" name=\"user_chk2\" id=\"chk2\" value=\"개인정보 수집∙이용 동의\">개인정보 수집∙이용 동의<br>\n");
      out.write("                                            <input class=\"chk1\" type=\"checkbox\" name=\"user_chk3\" id=\"chk3\" value=\"무료배송, 할인쿠폰 등 혜택/정보 수신 동의\">무료배송, 할인쿠폰 등 혜택/정보 수신 동의<br>\n");
      out.write("                                            <input class=\"chk1\" type=\"checkbox\" name=\"user_chk4\" id=\"chk4\" value=\"본인은 만 14세 이상입니다.\">본인은 만 14세 이상입니다.<br>\n");
      out.write("                                        </label>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <button type='submit'>가입하기</button>\n");
      out.write("                                    </li>\n");
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </main>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
